{"uuid": "11b13f5e-6350-4e8c-bcaf-7a06bf7e03c1", "children": ["6e07a07f-27f9-40c4-9eee-33dc91f8579a"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver_83.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\yuriy\\pycharmprojects\\testselenium\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\yuriy\\pycharmprojects\\testselenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\yuriy\\pycharmprojects\\testselenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\yuriy\\PycharmProjects\\testselenium\\pytest_selenium_simple\\tests\\conftest.py\", line 10, in browser\n    browser = webdriver.Chrome(\"../resources/chromedriver_83.exe\")\n  File \"c:\\users\\yuriy\\pycharmprojects\\testselenium\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\yuriy\\pycharmprojects\\testselenium\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1591722046865, "stop": 1591722046869}], "start": 1591722046865, "stop": 1591722047090}